### ISSUE TITLE
Are url_path really needed currently?

### ISSUE THREAD

**Issue by dmanners** [baldwin-agency/magento2-module-url-data-integrity-checker#39]
This is more a question than an issue so sorry if this is the wrong place to ask such questions.

As far as I know url_path is now deprecated in newer versions of Magento 2. My question here is would it make sense to only flag these errors on older version of Magento or if you are not supporting older versions could it simply be removed?

See https://github.com/magento/magento2/issues/9113#issuecomment-488790088

**Comment by hostep** [comment]
Hey David

You are talking about products, right? In that case the `url_path` has always been deprecated in all Magento 2 versions (not only newer versions). For categories, they are still valid.

As far as I know, for products they are still being used when filled in in the database for generating url rewrites which can lead to all kinds of bad things because it's a hidden field that's not exposed in the UI, so changing the `url_key` field of a product will result in no change since the hidden `url_path` will overwrite it.

So I think we should still warn about them if they are being detected in the database. You'd best remove them all in case they are still used in the database for products.

**Comment by dmanners** [comment]
Hi,

Thanks for the information. Yes I was not sure if it was just products or not but it seems they still get used for rewrites so probably best to keep it all active.
