### ISSUE TITLE
Call to undefined method Baldwin\UrlDataIntegrityChecker\Model\ResourceModel\Catalog\Product\UrlKeyCollection::getMainTable()

### ISSUE THREAD

**Issue by senders** [baldwin-agency/magento2-module-url-data-integrity-checker#8]
Hello,

I have installed it yesterday in  am magento 2.3.5p1 installation via composer.

CLI ist working.
But backend not.
I am getting this error:

Call to undefined method Baldwin\UrlDataIntegrityChecker\Model\ResourceModel\Catalog\Product\UrlKeyCollection::getMainTable()

kind regards

**Comment by hostep** [comment]
Hi @senders

Thanks for the report!
Unfortunately I'm unable to reproduce the problem on a vanilla Magento OS 2.3.5-p1 installation.
I'm guessing that some custom module might be interfering here, do you have some custom module installed which manipulates admin grids?

It would be great if you would be able to find a stacktrace which leads up to this error, I might be able to figure out how it happens then.

Honestly, I'm not super happy with how the grids are implemented in this module, Magento seems to always wants a database source for the data for grids, so I had to hack my way around it a bit since the data in this module doesn't come from a database table. And that might be one of the causes of this issue.

Thanks!

**Comment by hostep** [comment]
Closing due to lack of feedback.

**Comment by senders** [comment]
Today I have installed it again on a 2.4.2 installation and now again the same problem.

Call to undefined method Baldwin\UrlDataIntegrityChecker\Model\ResourceModel\Catalog\Product\UrlPathCollection\Interceptor::getMainTable()
Exception in /home/devsissel/public_html/vendor/swissup/module-checkout-fields/Plugin/Ui/Component/OrderListingData.php:42

seems to me that there is a conflict with Swissup firecheckout

**Comment by hostep** [comment]
Hi @senders, this sounds like a duplicate of https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/issues/15

I feel like this is a bug in the firecheckout module, maybe those developers can take a look at this issue in further detail?

**Comment by senders** [comment]
hi @hostep, I have created a ticket at swissup.
I hope they will address the problem.

**Comment by senders** [comment]
Swissup has fixed that problem very quickly in a new version 1.3.5 of swissup/module-checkout-fields.
Great!!

**Comment by hostep** [comment]
Awesome and thanks for the quick feedback!
